// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9-eV6sw3RjgTHqWT8TAaeS8jaWSlZ_a8',
    appId: '1:70274420052:web:fbb7ca895f33895bee0cc1',
    messagingSenderId: '70274420052',
    projectId: 'itachyon-97675',
    authDomain: 'itachyon-97675.firebaseapp.com',
    storageBucket: 'itachyon-97675.appspot.com',
    measurementId: 'G-8KXKSRK3PW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9DqaIy_wjOS-b5lZ1eVxtSuA0H3IHwXI',
    appId: '1:70274420052:android:e82a48a6489655c5ee0cc1',
    messagingSenderId: '70274420052',
    projectId: 'itachyon-97675',
    storageBucket: 'itachyon-97675.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7e_wWu-Yb-g5t2tBaLr43kNHvrdHokk0',
    appId: '1:70274420052:ios:797488eb69009788ee0cc1',
    messagingSenderId: '70274420052',
    projectId: 'itachyon-97675',
    storageBucket: 'itachyon-97675.appspot.com',
    iosClientId: '70274420052-o8rgqkecq9vrh471l6cfvc72trfvqpmr.apps.googleusercontent.com',
    iosBundleId: 'com.example.itachyon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7e_wWu-Yb-g5t2tBaLr43kNHvrdHokk0',
    appId: '1:70274420052:ios:797488eb69009788ee0cc1',
    messagingSenderId: '70274420052',
    projectId: 'itachyon-97675',
    storageBucket: 'itachyon-97675.appspot.com',
    iosClientId: '70274420052-o8rgqkecq9vrh471l6cfvc72trfvqpmr.apps.googleusercontent.com',
    iosBundleId: 'com.example.itachyon',
  );
}
